spring.application.name=backend
server.port=8081

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=hr
spring.datasource.password=hr

spring.jpa.database-platform=org.hibernate.community.dialect.OracleLegacyDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

#이 secret은 개발용입니다.
#실무에서는 GitHub에 올리면 안 되고 환경변수나 Secret Manager로 관리합니다.
jwt.secret=c2NzYS1pc3N1ZS10cmFja2VyLWRldi1qd3Qtc2VjcmV0LWtleS0yMDI2LTA1LTIx
jwt.access-token-validity-milliseconds=1800000
