server.port=${PORT:${SERVER_PORT:8081}}

spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=${JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.baseline-on-migrate=${FLYWAY_BASELINE_ON_MIGRATE:false}
spring.flyway.baseline-version=1
spring.flyway.locations=${FLYWAY_LOCATIONS:classpath:db/migration/postgresql}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

jwt.secret=${JWT_SECRET}
