server.port=${PORT:${SERVER_PORT:8081}}

spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=${JPA_DATABASE_PLATFORM:org.hibernate.community.dialect.OracleLegacyDialect}
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

jwt.secret=${JWT_SECRET}
